// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PharmaPlus.Core.Produits.Infrastructures.Data;

namespace PharmaPlus.Core.Produits.Migrations.Migrations
{
    [DbContext(typeof(ProduitsContext))]
    [Migration("20210925235347_InitDatabase")]
    partial class InitDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PharmaPlus.Core.Produits.Domain.Picture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Picture");
                });

            modelBuilder.Entity("PharmaPlus.Core.Produits.Domain.Produit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Ai_group_no")
                        .HasColumnType("int");

                    b.Property<string>("Brand_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Class_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Company_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descriptor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Drug_code")
                        .HasColumnType("int");

                    b.Property<int>("Drug_identification_number")
                        .HasColumnType("int");

                    b.Property<DateTime>("Expiry_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Last_update_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Number_of_ais")
                        .HasColumnType("int");

                    b.Property<int>("PictureId")
                        .HasColumnType("int");

                    b.Property<decimal>("Ppa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Purchase_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Sell_price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PictureId");

                    b.ToTable("Produit");
                });

            modelBuilder.Entity("PharmaPlus.Core.Produits.Domain.Produit", b =>
                {
                    b.HasOne("PharmaPlus.Core.Produits.Domain.Picture", "Picture")
                        .WithMany("Produits")
                        .HasForeignKey("PictureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Picture");
                });

            modelBuilder.Entity("PharmaPlus.Core.Produits.Domain.Picture", b =>
                {
                    b.Navigation("Produits");
                });
#pragma warning restore 612, 618
        }
    }
}
